config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tags
  resources :images
  resources :events, except: [:new]
  resources :categories, except: [:new] do
    member do
      post 'add_tag', to: 'categories#add_tag', as: :add_tag
      post 'remove_tag', to: 'categories#remove_tag', as: :remove_tag
    end
  end
  resources :chronologies do
    collection do
      get 'cards', to: 'chronologies#cards', as: :cards
      get 'view/:token', to: 'chronologies#view', as: :view
      get 'tagged', to: 'chronologies#tagged', as: :tagged
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  get 'login' => 'user_sessions#new', :as => :login
  get 'oauth/callback', to: 'oauth#callback'
  get 'oauth/:provider', to: 'oauth#oauth', as: 'auth_at_provider'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: %i[create]

  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/top_controller.rb
# frozen_string_literal: true

# for top page
class TopController < ApplicationController
  skip_before_action :require_login

  layout :false

  def index; end
end

app/views/top/index.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title AnyHistory
    %link{:href => "img/favicon.ico", :rel => "icon"}/
    / CSS FILES
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    :css
      .wrap::before {
        position: absolute;
        height: 100vh;
        width: 100vw;
        content: '';
        z-index: 1;
        background-color: rgba(0,0,0,0.5);
      }
      .lead {
        font-size: 1.175em;
        font-weight: 300;
      }
      .uk-logo img {
        height: 28px;
      }
  %body.uk-light.wrap.uk-background-norepeat.uk-background-cover.uk-background-center-center.uk-cover-container.uk-background-secondary
    %img{:alt => "", "data-src" => "https://picsum.photos/id/24/1200/900", "data-srcset" => "https://picsum.photos/id/24/640/700 640w,\r\n\t\t             https://picsum.photos/id/24/960/700 960w,\r\n\t\t             https://picsum.photos/id/24/1200/900 1200w,\r\n\t\t             https://picsum.photos/id/24/2000/1000 2000w", "data-uk-cover" => "", "data-uk-img" => "", :sizes => "100vw"}/
    .uk-flex.uk-flex-center.uk-flex-middle.uk-height-viewport.uk-position-z-index.uk-position-relative{"data-uk-height-viewport" => "min-height: 400"}
      / NAV
      .uk-position-top
        .uk-container.uk-container-small
          %nav.uk-navbar-container.uk-navbar-transparent{"data-uk-navbar" => ""}
            .uk-navbar-left
              .uk-navbar-item
                %a.uk-logo{:href => root_path}
                  %i{ 'data-uk-icon': 'history' }
                  AnyHistory
            .uk-navbar-right
              %ul.uk-navbar-nav
                %li
                  %a.uk-navbar-toggle{"data-uk-navbar-toggle-icon" => "", "data-uk-toggle" => "", :href => "#offcanvas-nav"}
      / /NAV
      / TEXT
      .uk-container.uk-container-small.uk-flex-auto.uk-text-center{"data-uk-scrollspy" => "target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300"}
        %h1.uk-heading-primary.animate.uk-invisible{:style => "font-weight: 700;"} Create Your Any History.
        %h2.uk-heading-primary.animate.uk-invisible{:style => "font-weight: 700;"} And Share It.
        .uk-margin-auto.animate.uk-invisible{:class => "uk-width-4-5@m"}
          -# %p.lead Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad, reiciendis maxime, facilis nam natus incidunt provident.
        .uk-margin-medium-top.animate.uk-invisible{"data-uk-margin" => "", "data-uk-scrollspy-class" => "uk-animation-fade uk-invisible"}
          - unless logged_in?
            = link_to 'LOGIN', auth_at_provider_path(provider: :google), class: 'uk-button uk-button-default uk-button-large uk-width-2-3 uk-width-auto@s', 'data-uk-icon': 'arrow-right'
          - else
            = link_to  cards_chronologies_path, class: 'uk-button uk-button-primary uk-button-large uk-width-2-3 uk-width-auto@s' do
              %i{ 'data-uk-icon': 'history' }
              Show Chronologies
      .uk-position-bottom-center.uk-position-small
        %span.uk-text-small.uk-text-center
          © 2019 |
          %a{:href => "https://github.com/yukimura1227/any_history", title: 'AnyHistory'} AnyHistory
          | Built with
          %a{"data-uk-tooltip" => "", :href => "http://getuikit.com", :target => "_blank", :title => "Visit UIkit 3 site"}
            %span{"data-uk-icon" => "uikit"}
      / /FOOT
    / OFFCANVAS
    #offcanvas-nav{"data-uk-offcanvas" => "flip: true; overlay: false"}
      .uk-offcanvas-bar.uk-offcanvas-bar-animation.uk-offcanvas-slide
        %button.uk-offcanvas-close.uk-close.uk-icon{"data-uk-close" => "", :type => "button"}
        %ul.uk-nav.uk-nav-default
          - if logged_in?
            %li.uk-active
              = link_to 'Chronologies', cards_chronologies_path
            %li.uk-parent
              Manage Your Chronologies
              %ul.uk-nav-sub
                %li
                  = link_to 'chronologies', chronologies_path
                %li
                  = link_to 'categories', categories_path
                %li
                  = link_to 'events', events_path
          %li
            - unless logged_in?
              = link_to 'LOGIN', auth_at_provider_path(provider: :google), class: 'uk-button uk-button-default uk-button-large uk-width-2-3 uk-width-auto@s', 'data-uk-icon': 'arrow-right'
            - else
              = link_to 'LOGOUT', logout_path, method: :delete
        %h3 About Any History
        %p todo write explain.
    = javascript_include_tag "application"