config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tags
  resources :images
  resources :events, except: [:new]
  resources :categories, except: [:new] do
    member do
      post 'add_tag', to: 'categories#add_tag', as: :add_tag
      post 'remove_tag', to: 'categories#remove_tag', as: :remove_tag
    end
  end
  resources :chronologies do
    collection do
      get 'cards', to: 'chronologies#cards', as: :cards
      get 'view/:token', to: 'chronologies#view', as: :view
      get 'tagged', to: 'chronologies#tagged', as: :tagged
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  get 'login' => 'user_sessions#new', :as => :login
  get 'oauth/callback', to: 'oauth#callback'
  get 'oauth/:provider', to: 'oauth#oauth', as: 'auth_at_provider'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: %i[create]

  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/chronology.rb
# for Chronology
class Chronology < ApplicationRecord
  has_secure_token
  belongs_to :user
  has_many :categories, dependent: :destroy
  belongs_to :image, optional: true
end

app/controllers/chronologies_controller.rb
class ChronologiesController < ApplicationController
  before_action :set_chronology, only: [:show, :edit, :update, :destroy]
  before_action :set_chronologies, only: %i[index]
  before_action :set_all_chronologies, only: %i[cards]

  # GET /chronologies
  # GET /chronologies.json
  def index
  end

  # GET /chronologies/1
  # GET /chronologies/1.json
  def show
  end

  def cards
  end

  def view
    @chronology =
      Chronology
      .includes(categories: :taggings)
      .find_by(token: params[:token])
  end

  def tagged
    tagged_category_ids = Category.tagged_with(params[:filter_tags]).pluck(:id)
    @events = Event.where(category_id: tagged_category_ids).order(:created_at)
  end

  # GET /chronologies/new
  def new
    @chronology = Chronology.new
  end

  # GET /chronologies/1/edit
  def edit
  end

  # POST /chronologies
  # POST /chronologies.json
  def create
    @chronology = Chronology.new(chronology_params)
    @chronology.user = current_user

    respond_to do |format|
      if @chronology.save
        format.html { redirect_to @chronology, notice: 'Chronology was successfully created.' }
        format.json { render :show, status: :created, location: @chronology }
      else
        format.html { render :new }
        format.json { render json: @chronology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chronologies/1
  # PATCH/PUT /chronologies/1.json
  def update
    respond_to do |format|
      if @chronology.update(chronology_params)
        format.html { redirect_to @chronology, notice: 'Chronology was successfully updated.' }
        format.json { render :show, status: :ok, location: @chronology }
      else
        format.html { render :edit }
        format.json { render json: @chronology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chronologies/1
  # DELETE /chronologies/1.json
  def destroy
    @chronology.destroy
    respond_to do |format|
      format.html { redirect_to chronologies_url, notice: 'Chronology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_chronology
    @chronology =
      if current_user.admin?
        Chronology.find_by(id: params[:id])
      else
        Chronology.find_by(id: params[:id], user_id: current_user.id)
      end
  end

  def set_chronologies
    @chronologies =
      if current_user.admin?
        Chronology.all
      else
        Chronology.where(user: current_user)
      end
  end

  def set_all_chronologies
    @chronologies = Chronology.includes(:user).all
  end

  def chronology_params
    params.require(:chronology).permit(:title, :description, :token, :image_id)
  end
end

app/views/chronologies/_category_and_timeline.html.haml
-# category
-# chronology
%section.section.intro.uk-text-lead
  = "Category: #{category.theme}"
  - Tag.all.each do |tag|
    %span{ id: "js-tag-form-category-#{category.id}-tag-#{tag.id}"}
      = render 'tag_form', category: category, tag: tag
= form_for Image.new, html: { class: "form form-inline image mydropzone uk-placeholder uk-padding-remove-vertical uk-background-default uk-text-success" }, data: { 'link-target': "#js-event-form-#{category.id}"} do |f|
  .fallback
    = f.file_field :file
= form_for Event.new, remote: true, html: { class: "form form-inline uk-margin-small-bottom", id: "js-event-form-#{category.id}" } do |f|
  = f.text_field :title, class: "form-control js-clear_target_#{category.id}", required: true, placeholder: 'title'
  = f.error_span(:title)
  = f.hidden_field :chronology_id, value: chronology.id
  = f.hidden_field :category_id, value: category.id
  = f.hidden_field :image_id, value: ''
  = f.number_field :year, class: 'form-control', required: true, placeholder: 'year', min: 1900, max: 2050, value: Date.current.year
  = f.number_field :month, class: 'form-control', required: true, placeholder: 'month', min: 1, max: 12, value: Date.current.month
  = f.text_field :url, class: "form-control  js-clear_target_#{category.id}", required: false, placeholder: 'url'
  = f.submit nil,class: 'btn btn-success'
%section.timeline
  .js-timeline-content{ id: "js-timeline-content-#{category.id}" }
    = render 'chronologies/timeline_content', events: category.events
  .arrows
    %button.arrow.arrow__prev.disabled{:disabled => "disabled"}
      %img{:alt => "prev timeline arrow", :src => "https://s3-us-west-2.amazonaws.com/s.cdpn.io/162656/arrow_prev.svg"}/
    %button.arrow.arrow__next
      %img{:alt => "next timeline arrow", :src => "https://s3-us-west-2.amazonaws.com/s.cdpn.io/162656/arrow_next.svg"}/

app/views/chronologies/_form.html.haml
:javascript
  $(function (){
    Dropzone.autoDiscover = false;
    $(".mydropzone").each( (idx, element) => {
      var option = {
        maxFilesize: 1,
        paramName: 'image[file]',
        success: function(file, response){
          append_target_id = $(element).data('link-target');
          append_target = $(append_target_id);
          append_target.find('#chronology_image_id').val(response.id);
          append_target.prepend('<div class="uk-text-center"><img src="' + file.dataURL + '" style= "max-height: 50px;"/></div>');
          $(element).remove();
        }
      };
      new Dropzone(element, option);
    });
    $(".mydropzone").append('<div class="dz-default dz-message"><span>Drop image files here or click to upload.</span>');
  });
= form_for Image.new, html: { class: "form form-inline image mydropzone uk-placeholder" }, data: { 'link-target': '#js-chronology-form'} do |f|
  .form-group
    .fallback
      = f.file_field :file
= form_for @chronology, html: { class: 'form form-horizontal chronology', id: 'js-chronology-form'} do |f|
  = f.hidden_field :image_id, value: ''
  .form-group
    = f.label :title, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control', required: true
    = f.error_span(:title)
  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, class: 'form-control', required: true
    = f.error_span(:description)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), chronologies_path, :class => 'btn btn-default'

app/views/chronologies/_tag_form.html.haml
-# tag: required
-# category: required
- category_tags = category.tag_list
- checked = category_tags.include?(tag.name)
- tag_post_url = checked ? remove_tag_category_path(category) : add_tag_category_path(category)
= form_for Tag.new, remote: true, url: tag_post_url, authenticity_token: true, html: { class: "form form-inline uk-display-inline"} do |f|
  = f.hidden_field :tag, value: tag.name
  = f.check_box :tags, { multiple: true, checked: checked , class: 'check-box-like-tag', id: "category_#{category.id}_tag_#{tag.id}" }, tag.name
  %label{ for: "category_#{category.id}_tag_#{tag.id}", onclick: 'Rails.fire(this.form, "submit");' }
    = tag.name

app/views/chronologies/_timeline_content.html.haml
-# events
%ol
  - events.includes(:image).decorate.each do |e|
    %li
      %div
      .uk-flex.uk-flex-column
        %time.uk-text-center{ 'uk-tooltip': e.category.chronology.user.email }
          =format("%d/%02d", e.year, e.month)
        - if e.image.present?
          = image_tag url_for(e.image.file), style: 'max-height: 100px; max-width: 100px;'
        %span.text-vertical
          = e.event_link

app/views/chronologies/cards.html.haml
- content_for :head do
  = stylesheet_link_tag 'chronologies/cards.css'
-# %header#site-head
  .uk-container.uk-container-expand
    .uk-grid.uk-grid-medium.uk-flex.uk-flex-middle{"data-uk-grid" => ""}
      .uk-width-expand
        %form#search-form{:action => ""}
          .uk-inline.uk-width-1-1
            %span.uk-form-icon.uk-form-icon-flip{'data-uk-icon': 'icon: search'}
            %input.uk-input.uk-width-1-1.search-fld{autofocus: '', placeholder: 'Type your search', type: 'text'}/
            %a.search-filter{'data-uk-filter-control': '[data-tags*='']', hidden: '', href: '#'} Search
%section.uk-section.uk-section-small.uk-padding-remove-bottom
  .uk-container.uk-container-expand.uk-margin-large-bottom
    .uk-grid.uk-grid-medium.uk-grid-match.js-filter{:class => "uk-child-width-1-2@s uk-child-width-1-3@m uk-child-width-1-4@l uk-child-width-1-5@xl", "data-uk-grid" => "masonry: true", "data-uk-sortable" => "handle: .drag-icon"}
      .nature-card{'data-tags': 'a beautiful landscape - nature outdoor'}
        .uk-card.uk-card-small.uk-card-default
          = link_to new_chronology_path, class: 'uk-position-center' do
            %div{ 'uk-icon': 'icon: plus-circle; ratio: 8' }
      - @chronologies.each do |chronology|
        .nature-card{'data-tags': 'a beautiful landscape - nature outdoor'}
          .uk-card.uk-card-small.uk-card-default
            .uk-card-header
              .uk-grid.uk-grid-small.uk-text-small{'data-uk-grid': ''}
                .uk-width-expand
                  %h6.uk-margin-small-bottom.uk-margin-remove-adjacent.uk-text-bold
                    = link_to chronology.title, view_chronologies_path(chronology.token)
                .uk-width-auto.uk-text-right.uk-text-muted
                  %span{'data-uk-icon': 'icon:clock; ratio: 0.8'}
                  = l chronology.created_at, format: :short
            .uk-card-media
              .uk-inline-clip.uk-transition-toggle.uk-width-1-1.uk-text-center{:tabindex => "0"}
                = link_to view_chronologies_path(chronology.token) do
                  - image_file = chronology.image.present? ? url_for(chronology.image.file) : asset_url('note_kurorekishi.png')
                  = image_tag image_file, style: 'max-height: 300px; max-width: 300px;', class: 'lazy', data: { height: '250', width: 300, 'uk-img': '', src: image_file }
                .uk-transition-slide-bottom.uk-position-bottom.uk-overlay.uk-overlay-primary
                  = chronology.description
            .uk-card-footer
              .uk-grid.uk-grid-small.uk-grid-divider.uk-flex.uk-flex-middle{"data-uk-grid" => ""}
                .uk-width-expand.uk-text-small
                  = chronology.user.email
= javascript_include_tag 'chronologies/cards'

app/views/chronologies/edit.html.haml
- model_class = Chronology
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/chronologies/index.html.haml
- model_class = Chronology
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:token)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @chronologies.each do |chronology|
      %tr
        %td= link_to chronology.id, chronology_path(chronology)
        %td= chronology.title
        %td= chronology.description
        %td= chronology.user_id
        %td= chronology.token
        %td=l chronology.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), chronology_path(chronology), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_chronology_path(chronology), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), chronology_path(chronology), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_chronology_path, :class => 'btn btn-primary'

app/views/chronologies/new.html.haml
- model_class = Chronology
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/chronologies/show.html.haml
- model_class = Chronology
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @chronology.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @chronology.description
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @chronology.user_id
%p
  %strong= model_class.human_attribute_name(:token) + ':'
  %br
  = @chronology.token


= link_to t('.back', :default => t("helpers.links.back")), chronologies_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_chronology_path(@chronology), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), chronology_path(@chronology), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/chronologies/tagged.html.haml
- content_for :head do
  = stylesheet_link_tag 'chronologies/view.css'
  = javascript_include_tag 'chronologies/view.js'
= form_tag tagged_chronologies_path, method: 'get' do
  .uk-inline.uk-width-1-1
    .uk-inline
      - Tag.all.each do |tag|
        - checked = params[:filter_tags]&.include? tag.name # TODO
        = check_box_tag 'filter_tags[]', tag.name, checked, { multiple: true, class: 'check-box-like-tag', id: "tag_#{tag.id}" }
        %label{ for: "tag_#{tag.id}" }
          = tag.name
    .uk-inline.uk-light
      = submit_tag 'Search', class: 'uk-button uk-button-primary'
%h1.uk-heading-xlarge.uk-text-left.uk-text-bold{style: 'color: white;'}
  ="#{params[:filter_tags]}で検索"

%section.timeline
  = render 'chronologies/timeline_content', events: @events

app/views/chronologies/view.html.haml
:javascript
  $(function (){
    Dropzone.autoDiscover = false;
    $(".mydropzone").each( (idx, element) => {
      var option = {
        maxFilesize: 1,
        paramName: 'image[file]',
        success: function(file, response){
          append_target_id = $(element).data('link-target');
          append_target = $(append_target_id);
          append_target.find('#event_image_id').val(response.id);
          append_target.prepend('<img src="' + file.dataURL + '" style= "max-height: 50px;"/>');
          $(element).remove();
        }
      };
      new Dropzone(element, option);
    });
    $(".mydropzone").append('<div class="dz-default dz-message"><span uk-icon="icon: cloud-upload"></span><span>Drop files here or click to upload.</span>');
  });
- content_for :head do
  = stylesheet_link_tag 'chronologies/view.css'
  = javascript_include_tag 'chronologies/view.js'
%h1.uk-heading-xlarge.uk-text-left.uk-text-bold{style: 'color: white;'}
  ="Chronology Title: #{t '.title', default: @chronology.title}"

.category_wrap
  - @chronology.categories.each do |c|
    = render 'category_and_timeline', category: c, chronology: @chronology
= form_for Category.new, remote: true, html: { class: "form form-inline uk-margin-small-bottom" } do |f|
  = f.text_field :theme, class: 'form-control', required: true, placeholder: 'theme'
  = f.hidden_field :chronology_id, value: @chronology.id
  = f.submit nil,class: 'btn btn-primary'