config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tags
  resources :images
  resources :events, except: [:new]
  resources :categories, except: [:new] do
    member do
      post 'add_tag', to: 'categories#add_tag', as: :add_tag
      post 'remove_tag', to: 'categories#remove_tag', as: :remove_tag
    end
  end
  resources :chronologies do
    collection do
      get 'cards', to: 'chronologies#cards', as: :cards
      get 'view/:token', to: 'chronologies#view', as: :view
      get 'tagged', to: 'chronologies#tagged', as: :tagged
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  get 'login' => 'user_sessions#new', :as => :login
  get 'oauth/callback', to: 'oauth#callback'
  get 'oauth/:provider', to: 'oauth#oauth', as: 'auth_at_provider'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: %i[create]

  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/category.rb
# frozen_string_literal: true

# for Category
class Category < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  belongs_to :chronology
  has_many :events, -> { order(:year, :month) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :set_some_category, only: %i[add_tag remove_tag]

  # GET /categories
  # GET /categories.json
  def index
    @categories =
      if current_user.admin?
        Category.all
      else
        Category.joins(:chronology).where(chronologies: { user_id: current_user.id })
      end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        @category_and_timeline_html = render_to_string partial: 'chronologies/category_and_timeline', locals: { category: @category, chronology: @category.chronology }
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
        format.js
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_tag
    @category.tag_list << params[:tag][:tag]
    @tag = Tag.find_by(name: params[:tag][:tag])
    @category.save
    @tag_form_html = render_to_string partial: 'chronologies/tag_form', locals: { category: @category, tag: @tag }
    respond_to do |format|
      format.js
    end
  end

  def remove_tag
    @category.tag_list.remove(params[:tag][:tag])
    @tag = Tag.find_by(name: params[:tag][:tag])
    @category.save
    @tag_form_html = render_to_string partial: 'chronologies/tag_form', locals: { category: @category, tag: @tag }
    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category =
      if current_user.admin?
        Category.find(params[:id])
      else
        Category.joins(:chronology).find_by(id: params[:id], chronologies: { user_id: current_user.id })
      end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_some_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:theme, :chronology_id)
  end
end

app/views/categories/_form.html.haml
= form_for @category, html: { class: "form form-horizontal category" } do |f|
  .form-group
    = f.label :theme, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :theme, class: 'form-control', required: true
    = f.error_span(:theme)
  .form-group
    = f.label :chronology_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :chronology_id, class: 'form-control', required: true
    = f.error_span(:chronology_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default'

app/views/categories/add_tag.js.erb
$('<%="#js-tag-form-category-#{@category.id}-tag-#{@tag.id}"%>').html('<%= j(@tag_form_html) %>');

app/views/categories/create.js.erb
<% if @category_and_timeline_html.present? %>
  $('.category_wrap').append('<%= j(@category_and_timeline_html) %>');
<% end %>

app/views/categories/edit.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:theme)
      %th= model_class.human_attribute_name(:chronology_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.id, category_path(category)
        %td= category.theme
        %td= category.chronology_id
        %td=l category.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/categories/remove_tag.js.erb
$('<%="#js-tag-form-category-#{@category.id}-tag-#{@tag.id}"%>').html('<%= j(@tag_form_html) %>');

app/views/categories/show.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:theme) + ':'
  %br
  = @category.theme
%p
  %strong= model_class.human_attribute_name(:chronology_id) + ':'
  %br
  = @category.chronology_id


= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'